### ISSUE TITLE
Recaf don't see newer version of Java

### ISSUE THREAD

**Issue by JunkBeat** [Col-E/Recaf-documentation#3]
Please help. I have jre 8 and 10 installed, as well as jdk 22. The JAVA_HOME and Path environment variables point to jdk 22, but Recaf doesn't seem to see this. I don’t know what to do.

![изображение_2024-05-04_182118428](https://github.com/Col-E/Recaf-documentation/assets/61349612/8c5559d5-db40-45d6-b74f-eeed802a4f36)

**Comment by Col-E** [comment]
`JAVA_HOME` isn't relevant.

If you have two JDK's in the path, whichever is first will be used.
